#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://shshinde31:saurabh-hs@journalcluster.hpqn1.mongodb.net/?retryWrites=true&w=majority&appName=JournalCluster
#      database: journaldb
#      auto-index-creation: true
#
#server:
#  port: 8082
#  servlet:
#    context-path: /journal